services:
  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - catalogdb
    environment:
      - DatabaseSettings__ConnectionString=mongodb://catalogdb:27017
      - DatabaseSettings__DatabaseName=CatalogDb
      - DatabaseSettings__BrandsCollection=Brands
      - DatabaseSettings__TypesCollection=Types
      - DatabaseSettings__ProductsCollection=Products
      - ASPNETCORE_ENVIRONMENT=Development

  basket.api:
    image: basket.api
    build:
      context: .
      dockerfile: Basket.API/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - basketdb
    environment:
      - CacheSettings__ConnectionString=basketdb:6379
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Discount=http://discount.grpc:8080

  discount.grpc:
    image: discount.grpc
    build:
      context: .
      dockerfile: Discount.GRPC/Dockerfile
    ports:
      - "8082:8080"
    environment:
      - ConnectionStrings__Sqlite=Data Source=/app/data/discount.db
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - discountdata:/app/data

  basketdb:
    image: redis:alpine
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  catalogdb:
    image: mongo
    container_name: catalogdb
    ports:
      - "27017:27017"
    volumes:
      - catalogdata:/data/db

volumes:
  catalogdata:
  discountdata:
